### ISSUE TITLE
Incorrect operator priority clash

### ISSUE THREAD

**Issue by cbarrick** [cbarrick/ripl#2]
When parsing the clause `foo(X) :- X = bar.`, the parser throws an operator priority clash.

**Comment by triska** [comment]
Chris, this is going to be so awesome! I'm really looking forward to using your Prolog implementation in the future.

**Comment by cbarrick** [comment]
Thanks for the encouragement!

I've got a lot of cool ideas about where I want to take the project, but first I need to take the time to get the fundamentals right. It will be a good while before I have anything running, and I'll be slowing down over the summer (not that development was very fast to begin with). But since I'm doing this on my own time, I'm more concerned with learning than deadlines.

**Comment by triska** [comment]
That's definitely to be expected: Prolog is a quite general language that is not so easy to implement. Just look at other systems: 25&nbsp;years and counting! Still, I'm always delighted also by small improvements, so thank you for sharing this!
